# Generated by Django 4.1 on 2022-08-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="Img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="post", name="slug", field=models.CharField(max_length=13),
        ),
    ]
