# Generated by Django 4.1 on 2022-08-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogcomment_post_img_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="Img",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="images/blogPost.html"
            ),
        ),
    ]
